---
title: "Table1"
output: html_document
---


```{r setup, include=FALSE}
library('knitr')
knitr::opts_chunk$set(cache=TRUE)
opts_chunk$set(fig.path = "/Users/sarahurbut/Dropbox/PaperEdits/Paper/Figures/") 
source("../../Analysis/normfuncs.R")
```

##Heterogeneity Analysis

First, we asked in how many tissues is a QTL signficiant. 
```{r loaddata,echo=F}

lfsr=read.table("../../Results_Data/withzerolfsr.txt")[,-1]
lfsr[lfsr<0]=0
lfsr.nobrain=read.table("../../withoutbrain/nobrainlfsr.txt")[,-1]
lfsr.brain.only=read.table("../../BrainOnly/brainonlylfsr.txt")[,-1]

tissue.names=as.character(read.table("../../Data/abbreviate.names.txt")[,2])
colnames(lfsr)=tissue.names
colnames(lfsr.nobrain)=tissue.names[-c(7:16)]
colnames(lfsr.brain.only)=tissue.names[c(7:16)]


maxbeta=read.table("../../Data/maxbetahats.txt")
maxz=read.table("../../Data/maxz.txt")
standard.error=read.table("../../Data/standard.error.txt")
pm.mash=as.matrix(read.table("../../Results_Data/withzeroposterior.means.txt")[,-1])
pm.mash.beta=pm.mash*standard.error

pm.mash.nobrain=as.matrix(read.table("../../withoutbrain/nobrainposterior.means.txt")[,-1])*standard.error[,-c(7:16)]

pm.mash.brain.only=as.matrix(read.table("../../BrainOnly//brainonlyposterior.means.txt")[,-1])*standard.error[,c(7:16)]

thresh=0.05
```

Here, we show the Proportion of Sharing by Sign:

```{r generate tablestt}
sigmat=(lfsr<=thresh)
nsig= rowSums(sigmat)
(signall=mean(het.norm(pm.mash.beta[nsig>0,])>0))

##show that results are robust in global analysis###
sigmat=(lfsr[,-c(7:16)]<=thresh)
nsig= rowSums(sigmat)
(signall.nobrain=mean(het.norm(pm.mash.beta[,-c(7:16)])>0))

sigmat=(lfsr[,c(7:16)]<=thresh)
nsig= rowSums(sigmat)
(signall.brainonly=mean(het.norm(pm.mash.beta[nsig>0,c(7:16)])>0))

####SHow that results are robust in specific analysis

sigmat=(lfsr.nobrain<=thresh)
nsig= rowSums(sigmat)
(signnobrain=mean(het.norm(pm.mash.nobrain[nsig>0,])>0))


sigmat=(lfsr.brain.only<=thresh)
nsig= rowSums(sigmat)
(signbrainonly=mean(het.norm(pm.mash.brain.only[nsig>0,])>0))
```

Here, we show heterogeneity by magnitude:

```{r}

sigmat=(lfsr<=thresh)
nsig= rowSums(sigmat)
(magall=mean(het.norm(pm.mash.beta[nsig>0,])>0.5))


##show that results are robust###
sigmat=(lfsr[,-c(7:16)]<=thresh)
nsig= rowSums(sigmat)
(magall.excludingbrain=mean(het.norm(pm.mash.beta[nsig>0,-c(7:16)])>0.5))

sigmat=(lfsr[,c(7:16)]<=thresh)
nsig= rowSums(sigmat)
(magall.brainonly=mean(het.norm(pm.mash.beta[nsig>0,c(7:16)])>0.5))


##show that results are robust###
sigmat=(lfsr.nobrain<=thresh)
nsig= rowSums(sigmat)
(magnobrain=mean(het.norm(pm.mash.nobrain[nsig>0,])>0.5))

sigmat=(lfsr.brain.only<=thresh)
nsig= rowSums(sigmat)
(magbrain=mean(het.norm(pm.mash.brain.only[nsig>0,])>0.5))
```