---
title: "NumberofTissuesSharedbyMagnitudeandSign"
output: pdf_document
---

In this document, we generate plots for Heterogeneity Distributions

```{r loaddata,echo=FALSE}
library('knitr')

knitr::opts_chunk$set(cache=TRUE)
opts_chunk$set(fig.path = "/Users/sarahurbut/Dropbox/PaperEdits/Paper/Figures/") 

source("../Analysis/normfuncs.R")
maxbeta=read.table("../Data/maxbetahats.txt")
maxz=read.table("../Data/maxz.txt")
standard.error=maxbeta/maxz
#standard.error=read.table("../Data/standard.error.txt")
#pm.mash=as.matrix(read.table("../../Dropbox/Aug12/Aug13withEDposterior.means.txt")[,-1])
#lfsr=as.matrix(read.table("../Data/Aug13withEDlfsr.txt")[,-1])
lfsr=read.table("../../Dropbox/withzero/withzerolfsr.txt")[,-1]
pm.mash=as.matrix(read.table("../../Dropbox/withzero/withzeroposterior.means.txt")[,-1])


pm.mash.beta=pm.mash*standard.error

pm.mash.nobrain=as.matrix(read.table("../withoutbrain/nobrainposterior.means.txt")[,-1])*standard.error[,-c(7:16)]

pm.mash.brain.only=as.matrix(read.table("../..//Dropbox/BrainOnly//brainonlyposterior.means.txt")[,-1])*standard.error[,c(7:16)]

```

Let's plot heterogneity by magnitude from the global analysis.

```{r hindexplotmagnitude,echo=FALSE,fig.height=5,fig.width=10}
thresh=0.05
### now make with all tissue effects


par(mar=c(4,4,2,1))
par(oma=c(8,4,0,0) + 0.1)
par(mfrow=c(1,3))


sigmat=(lfsr<=thresh)
nsig= rowSums(sigmat)

hist((het.func(het.norm(effectsize=pm.mash.beta[nsig>0,]),threshold=0.5)),main="",xlab="",breaks=0.5:44.5,col="grey",freq=FALSE,ylim=c(0,0.5),xaxt="n")
axis(1, at=seq(1, 44, by=1), labels=c(1:44))#,ylim=c(0,0.6))#,ylim=c(0,0.6))
mtext("All Tissues")

par(mar=c(4,4,2,1))
sigmat=(lfsr[,-c(7:16)]<=thresh)
nsig= rowSums(sigmat)

hist((het.func(het.norm(effectsize=pm.mash.beta[nsig>0,-c(7:16)]),threshold=0.5)),main="",xlab="",breaks=0.5:34.5,col="grey",freq=FALSE,ylim=c(0,0.65),xaxt="n")
axis(1, at=seq(1, 34, by=1), labels=c(1:34))#,ylim=c(0,0.6))
mtext("Non-Brain Tissues")

par(mar=c(4,4,2,1))
sigmat=(lfsr[,c(7:16)]<=thresh)
nsig= rowSums(sigmat)


brain.norm=het.norm(effectsize=pm.mash.beta[nsig>0,c(7:16)])
hist(het.func(brain.norm,threshold=0.5),main="",xlab="",breaks=0.5:10.5,col="grey",freq=FALSE,xaxt="n",ylim=c(0,0.9))
axis(1, at=seq(1, 10, by=1), labels=c(1:10))
mtext("Brain Tissues")

title(xlab="Number of Tissues Shared (by magnitude)", outer=TRUE,line=3,cex.lab=3)
````




Now, let's make the same plot with all tissue effects measuring the number of tissues which have a sign equivalent to max effect:
````{r hindexplotsign,echo=FALSE,fig.height=5,fig.width=10}

sign.func=function(normeffectsize){apply(normeffectsize,1,function(x)(sum(x>0)))}
par(mar=c(4,4.5,2,1))
par(oma=c(8,4,0,0) + 0.1)
par(mfrow=c(1,3))



sigmat=(lfsr<=thresh)
nsig= rowSums(sigmat)

hist(sign.func(het.norm(effectsize=pm.mash.beta[nsig>0,])),main="",xlab="",breaks=0.5:44.5,col="grey",freq=FALSE,#ylim=c(0,0.4),
     xaxt="n",ylim=c(0,0.5))
axis(1, at=seq(1, 44, by=1), labels=c(1:44))#,ylim=c(0,0.6))
mtext("All Tissues")


sigmat=(lfsr[,-c(7:16)]<=thresh)
nsig= rowSums(sigmat)

hist((sign.func(het.norm(effectsize=pm.mash.beta[nsig>0,-c(7:16)]))),main="",xlab="",breaks=0.5:34.5,col="grey",freq=FALSE,ylim=c(0,0.65),#ylim=c(0,0.14),
     xaxt="n")
axis(1, at=seq(1, 34, by=1), labels=c(1:34))#,ylim=c(0,0.6))
mtext("Non-Brain Tissues")

sigmat=(lfsr[,c(7:16)]<=thresh)
nsig= rowSums(sigmat)


brain.norm=het.norm(effectsize=pm.mash.beta[nsig>0,c(7:16)])
hist(sign.func(brain.norm),main="",xlab="",breaks=0.5:10.5,col="grey",freq=FALSE,xaxt="n",ylim=c(0,0.9))
axis(1, at=seq(1, 10, by=1), labels=c(1:10))
mtext("Brain Tissues")

title(xlab="Number of Tissues Shared (by sign)", outer=TRUE,line=3,cex.lab=3)
```
```

