---
title: "uk3"
output: pdf_document
---
Here we plot the correlation matrix and the first 3 eigenvectors of Uk3.

```{r,fig.show='hide'}
library('knitr')

knitr::opts_chunk$set(cache=TRUE)
opts_chunk$set(fig.path = "/Users/sarahurbut/Dropbox/PaperEdits/Paper/Figures/") 
covmat=readRDS("../Data/covmatAug13withED.rds")

z.stat=read.table("../Data/maxz.txt")
names=colnames(z.stat)
pis=readRDS("../Data/pisAug13withED.rds")$pihat
pi.mat=matrix(pis,ncol=54,nrow=22,byrow = T)
```

```{r corplotuk3,fig.height=10,fig.width=10}
library(gplots)
library(ggplot2)
library('colorRamps')
#install.packages("fields")
library(fields)
k=3
hclust.2=function (d, method = "average", members = NULL) {hclust(d, method, members)}
  x=cov2cor(covmat[[k]])
x[x<0]=0
  colnames(x)=names
  rownames(x)=names


h=read.table("../Analysis/uk3rowindices.txt")[,1]
```

heatmap:

```{r heatmapuk3final,fig.height=10,fig.width=10}

smat=(x[h,h])
smat[lower.tri(smat)] <- NA


heatmap.2(smat,#symm=TRUE,
          Rowv=FALSE,Colv=FALSE,
          dendrogram="none",density="none",trace="none",#col=redblue,
          col=blue2green(256),
          main=paste0("Cov2CorUk3"),
          cexRow=0.5,cexCol=0.5,cex.main=0.5,labCol="")
```

As square:

```{r heatmapuk3square,fig.height=10,fig.width=10}

smat=(x[h,h])


heatmap.2(smat,#symm=TRUE,
          Rowv=FALSE,Colv=FALSE,
          dendrogram="none",density="none",trace="none",#col=redblue,
          col=blue2green(256),
          main=paste0("Cov2CorUk3"),
          cexRow=0.5,cexCol=0.5,cex.main=0.5,labCol="")
```

```{r cormapuk3,fig.height=10,fig.width=10}

missing.tissues=c(7,8,19,20,24,25,31,34,37)
color.gtex=read.table("../Data/GTExColors.txt",sep = '\t', comment.char = '')[-missing.tissues,]
col = as.character(color.gtex[,2])

library('corrplot')


corrplot((x[h,h]),type="upper",cl.lim=c(0,1),tl.col=col[h],tl.cex=0.8,method="color",col=rep(blue2green(256),2))

colnames(x)=NULL
rownames(x)=rep(".",44)
corrplot((x[h,h]),type="upper",cl.lim=c(0,1),tl.col=col[h],tl.cex=8,method="color",col=rep(blue2green(256),2))


```


