---
title: "diff"
output: html_document
---

Here I, selected examples in which :
1) the mean effect across brains was in a different direction as the mean effect in other tissues
2) The absolute difference in mean brain raw z statistic and mean 'other' raw z statistic was greater than a threshold (here 6 left me with a reasonable number of examples, 12).

```{r echo=FALSE,cache=T}
maxz=read.table("../Data/maxz.txt")
z.stat=maxz
posterior.means=read.table("../Data/Aug13withEDposterior.means.txt")[,-1]
lfsr=read.table("~/Dropbox/Aug12/Aug13withEDlfsr.txt")[,-1]

colnames(posterior.means)=colnames(maxz)
brainmean=apply(maxz,1,function(x){mean(x[7:16])})

othermean=apply(maxz,1,function(x){mean(x[-c(7:16)])})
a=which(brainmean*othermean<0)
diff=abs(brainmean-othermean)
t=which(brainmean*othermean<0&diff>6)

```

```{r echo=FALSE}
col.func=function(lfsr,posterior.means,j){
  R=ncol(posterior.means)
  lfsr.mat=as.matrix(lfsr)
  col.mat=NULL
  for(r in 1:R){
 if (lfsr.mat[j,r]<=0.05) {
      col.mat[r]="green"
    } else if (lfsr.mat[j,r]<0.5) {
      col.mat[r]="orange"
    } else if (lfsr.mat[j,r]>=0.50) {
      col.mat[r]="red"
    } 
  }
  return(col.mat)
}

```

```{r, echo=FALSE}
for(i in t){
  par(mfrow=c(1,2))
  barplot(as.numeric(maxz[i,]),las=2,cex.names=0.5,main=paste0("ZMLE:",strsplit(rownames(z.stat)[i], "[.]")[[1]][1]))
  barplot(as.numeric(posterior.means[i,]),las=2,cex.names=0.5,main=paste0("E(Z|D):",strsplit(rownames(z.stat)[i], "[.]")[[1]][1]),col=col.func(lfsr=lfsr,posterior.means=posterior.means,j = i))
}


write.table(rownames(z.stat)[t],"~/Dropbox/oppositegenes.txt")
```



