---
title: "Add appropriate title here"
author: "Sarah Urbut"
output: workflowr::wflow_html
---

*Add text here.*

## Set up environment

```{r load-pkgs, message = FALSE}
# library('qtlcharts')
```

## Load data and MASH results

In the next code chunk, we load some GTEx summary statistics (e.g.,
average gene expression values, z scores), as well as some of the results
generated from the MASH analysis of the GTEx data.

```{r load-results}
data <- read.csv("../data/AvgExpr.csv.gz",header = TRUE)
out  <- readRDS("../data/MatrixEQTLSumStats.Portable.Z.rds")
maxz <- out$test.z
qtl.names <-
  sapply(1:length(rownames(maxz)),
         function(x) unlist(strsplit(rownames(maxz)[x], "[_]"))[[1]])
rownames(data) <- data[,1]
expr.data      <- data[,-1]
out    <- readRDS(paste("../output/MatrixEQTLSumStats.Portable.Z.coved.K3.P3",
                        "lite.single.expanded.V1.posterior.rds",sep = "."))
pmash <- out$posterior.means
lfsr  <- out$lfsr
colnames(lfsr) <- colnames(pmash) <- colnames(maxz)
rownames(lfsr) <- rownames(pmash) <- rownames(maxz)
expr.sort <- expr.data[rownames(expr.data)%in%qtl.names,]
a         <- match(qtl.names,rownames(expr.sort))
expr.sort <- expr.sort[a,]
missing.tissues    <- c(7,8,19,20,24,25,31,34,37)
exp.sort           <- expr.sort[,-missing.tissues]
colnames(exp.sort) <- colnames(maxz)
```



```{r definefunc}
plot_tissuespecific = function(tissuename,lfsr,curvedata,title,
                      thresh = 0.05,subset = 1:44) {
  index_tissue=which(colnames(lfsr) %in% tissuename);
  ybar=title
  ##create a matrix showing whether or not lfsr satisfies threshold
  sigmat = lfsr <= thresh;
  sigs=which(rowSums(sigmat[,index_tissue,drop=FALSE])==length(tissuename) &
             rowSums(sigmat[,-index_tissue,drop=FALSE])==0)
  sigs.it=which(lfsr[sigs,index_tissue]<thresh)
  iplotCurves(curvedata[sigs,subset],chartOpts=list(curves_xlab="Tissue",
              curves_ylab=ybar))
}

plot_tissuespecifictwo = function(tissuename,lfsr,ymax,curvedata,title,
                                  thresh=0.05,subset=1:44,exclude=0.01) {
  index_tissue=which(colnames(lfsr) %in% tissuename);
  ybar=title
  
  # Create a matrix showing whether or not lfsr satisfies threshold.
  sigmat = lfsr <= thresh;
  sigs=which(rowSums(sigmat[,index_tissue,drop=FALSE])==length(tissuename) &
             rowSums(sigmat[,-index_tissue,drop=FALSE])==0)
  norm.spec=density(curvedata[sigs,index_tissue])
  norm.other=density(curvedata[-sigs,index_tissue])
  xmin=min(norm.spec$x,norm.other$x)-1
  ymin=min(norm.spec$y,norm.other$y)
  xmax=max(norm.spec$x,norm.other$x)+1

  plot(norm.other,xlim = c(xmin,xmax),ylim=c(0,ymax),
       col="black",main=tissuename,xlab="log(RPKM)")
  
  lines(norm.spec,col="red")
  legend("right",legend = c("All Genes","Tissue Specific"),
         col=c("black","red"),pch=c(1,1))
  }

plot_tissuespecificthree = function(tissuename,lfsr,ymax,curvedata,title,
                                     thresh=0.05,subset=1:44,exclude=0.01) {
  index_tissue=which(colnames(lfsr) %in% tissuename);
  ybar=title
  
  ##create a matrix showing whether or not lfsr satisfies threshold
  sigmat = lfsr <= thresh;
  sigs=which(rowSums(sigmat[,index_tissue,drop=FALSE])==length(tissuename) &
             rowSums(sigmat[,-index_tissue,drop=FALSE])==0)
  norm.spec=ecdf(curvedata[sigs,index_tissue])
  norm.other=ecdf(curvedata[-sigs,index_tissue])
  plot(norm.other,ylim=c(0,ymax),
       col="black",main=tissuename,xlab="log(RPKM)")
  
    lines(norm.spec,col="red",cex=0.1)
	legend("right",legend = c("All Genes","Tissue Specific"),
	       col=c("black","red"),pch=c(1,1))
  } 
```

Here we compare quantiles and plot data:

Thyroid:

```{r thyroid}
plot_tissuespecifictwo(tissuename = "Thyroid",lfsr = lfsr,
                       curvedata = log(exp.sort),title = "Test",
                       thresh = 0.05,ymax=0.5 )
plot_tissuespecificthree(tissuename = "Thyroid",lfsr = lfsr,
                         curvedata = log(exp.sort),title = "Test",
                         thresh = 0.05,ymax=1 )
```

Testis:

```{r testis}
plot_tissuespecifictwo(tissuename = "Testis",lfsr = lfsr,
                       curvedata = log(exp.sort),title = "Test",
                       thresh = 0.05 ,ymax=0.5)
plot_tissuespecificthree(tissuename = "Testis",lfsr = lfsr,
                         curvedata = log(exp.sort),title = "Test",
                         thresh = 0.05 ,ymax=1)
```

Whole Blood:

```{r wholeblood}
plot_tissuespecifictwo(tissuename = "Whole_Blood",lfsr = lfsr,
                       curvedata = log(exp.sort),title = "Test",
                       thresh = 0.05,ymax=0.5)
plot_tissuespecificthree(tissuename = "Whole_Blood",lfsr = lfsr,
                         curvedata = log(exp.sort),title = "Test",
                         thresh = 0.05 ,ymax=1)
```

Muscle_Skeletal:

```{r ctf}
plot_tissuespecifictwo(tissuename = "Cells_Transformed_fibroblasts",
                       lfsr = lfsr,curvedata = log(exp.sort),title = "Test",
                       thresh = 0.05,ymax=0.5)
plot_tissuespecificthree(tissuename = "Cells_Transformed_fibroblasts",
                        lfsr = lfsr,curvedata = log(exp.sort),title = "Test",
                        thresh = 0.05 ,ymax=1)
```
