---
title: "heterogeneitywithandwithoutbrainformatthew"
output: html_document
---

```{r setup, include=FALSE}
library('knitr')
knitr::opts_chunk$set(cache=TRUE)
opts_chunk$set(fig.path = "/Users/sarahurbut/Dropbox/PaperEdits/Paper/Figures/") 
```

##Heterogeneity Analysis

First, we asked in how many tissues is a QTL signficiant. 
```{r,echo=F}
lfsr=read.table("~/Dropbox/Aug12/Aug13withEDlfsr.txt")[,-1]
lfsr[lfsr<0]=0
lfsr.nobrain=read.table("~/gtexresults_matrixash/withoutbrain/nobrainlfsr.txt")[,-1]
lfsr.brain.only=read.table("~/Dropbox/BrainOnly/brainonlylfsr.txt")[,-1]

tissue.names=as.character(read.table("~/gtexresults_matrixash/Data/abbreviate.names.txt")[,2])
colnames(lfsr)==tissue.names
colnames(lfsr.nobrain)=tissue.names[-c(7:16)]
colnames(lfsr.brain.only)=tissue.names[c(7:16)]
```

```{r smileyplot, echo=FALSE}

par(mar=c(4,4.5,2,1))
par(oma=c(3,3,3,3) )
thresh=0.05
par(mfrow=c(1,3))
sigmat=(lfsr<=thresh)
nsig= rowSums(sigmat)
hist(nsig[nsig>0],main="", nclass=45,xlab="Number of tissues",col="blue",ylim=c(0,7000))
mtext("AllTissues")
sigmat=(lfsr.nobrain<=thresh)
nsig= rowSums(sigmat)
hist(nsig[nsig>0],main="", nclass=35,xlab="Number of tissues",col="blue",ylim=c(0,7000))
mtext("Excluding Brain")

sigmat=(lfsr.brain.only<=thresh)
nsig= rowSums(sigmat)
hist(nsig[nsig>0],main="", nclass=35,xlab="Number of tissues",col="blue",ylim=c(0,7000))
mtext("Brain Only")
title("Number of Tissues Significant", outer=TRUE)

```

```{r}
standard.error=read.table("~/gtexresults_matrixash/Data/standard.error.txt")

pm.mash=as.matrix(read.table("~/Dropbox/Aug12/Aug13withEDposterior.means.txt")[,-1])

pm.mash.beta=pm.mash*standard.error

pm.mash.nobrain=as.matrix(read.table("~/gtexresults_matrixash/withoutbrain/nobrainposterior.means.txt")[,-1])*standard.error[,-c(7:16)]

pm.mash.brain.only=as.matrix(read.table("~/Dropbox/BrainOnly//brainonlyposterior.means.txt")[,-1])*standard.error[,c(7:16)]

```

But now, we can ask much more interesting questions.

```{r,echo=FALSE}
thresh_inconsistent=function(effectsize,thresh,sigs){
 z= sapply(seq(1:nrow(effectsize)),function(x){
l=sigs[x,];p=effectsize[x,];plow=p[which(l<thresh)];##grab only those posterior means that are 'significant'
if(length(plow)==0){return("FALSE")}##for ones who show no significants, they can't be heterogenous
else{pos=sum(plow>0);neg=sum(plow<0);pos*neg!=0}
})
return(sum(z==TRUE))}


het.norm=function(effectsize){
  t(apply(effectsize,1,function(x){
  x/x[which.max(abs(x))]
}))}


sign.norm=function(effectsize){
  t(apply(effectsize,1,function(x){
  x/sign(x[which.max(abs(x))])
}))}

sign.tissue.func=function(normdat){
  apply(normdat,1,function(x){
    sum(x<0)})}



het.func=function(normdat,threshold){
  apply(abs(normdat),1,function(x){sum(x>threshold)})}
```

```{r hindexplot,echo=FALSE}

par(mar=c(4,4.5,2,1))
par(oma=c(3,3,3,3) )
thresh=0.05
par(mfrow=c(1,3))


hist((het.func(het.norm(effectsize=pm.mash.beta),threshold=0.5)),main="",xlab="NumberofTissues",nclass=50,col="blue",freq=FALSE,ylim=c(0,0.6))
mtext("All Tissues")

hist((het.func(het.norm(effectsize=pm.mash.nobrain),threshold=0.5)),main="",xlab="NumberofTissues",nclass=40,col="blue",freq=FALSE,ylim=c(0,0.6))
mtext("Excluding Brain")

brain.norm=het.norm(effectsize=pm.mash.brain.only)
hist(het.func(brain.norm,threshold=0.5),main="",xlab="NumberofTissues",nclass=12,col="blue",freq=FALSE,ylim=c(0,0.6))
mtext("BrainOnly")

title("Number of Tissues >50% Max Effect", outer=TRUE)

```

```{r generate table}

(signall=mean(het.norm(pm.mash.beta)>0))
(signnobrain=mean(het.norm(pm.mash.nobrain)>0))
(signbrainonly=mean(het.norm(pm.mash.brain.only)>0))

####
(magall=mean(het.norm(pm.mash.beta)>0.5))
(magnobrain=mean(het.norm(pm.mash.nobrain)>0.5))
(magbrain=mean(het.norm(pm.mash.brain.only)>0.5))


####
(gene_cons_all=1-thresh_inconsistent(effect = pm.mash.beta,thresh=0.05,sigs =lfsr)/nrow(pm.mash.beta))
(gene_cons_nobrain=1-thresh_inconsistent(effect=pm.mash.nobrain,thresh = 0.05,sigs = lfsr.nobrain)/nrow(pm.mash.nobrain))
(gene_cons_brainonly=1-thresh_inconsistent(effect=pm.mash.brain.only,thresh = 0.05,sigs = lfsr.brain.only)/nrow(pm.mash.brain.only))
```

And plot the heatmaps of shared homogeneity:

```{r sharedhomogeneiety,echo=FALSE}



# library(gplots)
# library(ggplot2)
# #install.packages("fields")
# library(fields)
# library("gridGraphics")
# gl=list()
# 
# grab_grob <- function(){
#   grid.echo()
#   grid.grab()
# }
# 
# 
# ifile <- paste0(k,'homogeneity.png')
#     pdf(ifile)
#  

library('gplots')
R=44
a=het.norm(effectsize = pm.mash.beta)##for each gene, normalize by max effect


thresh=0.05
shared.het=matrix(NA,ncol=R,nrow=R)
colnames(shared.het)=rownames(shared.het)=tissue.names
for(i in 1:ncol(lfsr)){
  for(j in 1:ncol(lfsr)){
    sig.row=which(a[,i]>0.5)#&lfsr.mash[,i]<thresh)##one of the tissues close to max effect and satisfies lfsr threshold
    sig.col=which(a[,j]>0.5)#&lfsr.mash[,j]<thresh)
    shared.het[i,j]=length(intersect(sig.row,sig.col))/length(union(sig.row,sig.col))
 }

}

heatmap.2(shared.het,density="none",trace="none",dendrogram = "none",col=redblue(256),main="",cexRow=0.5,cexCol=0.5,symm = T)
mtext("All Tissues")

rm(a)
a=het.norm(effectsize = pm.mash.nobrain)##for each gene, normalize by max effect

shared.het.nobrain=matrix(NA,ncol=R-10,nrow=R-10)
colnames(shared.het.nobrain)=rownames(shared.het.nobrain)=tissue.names[-c(7:16)]
for(i in 1:ncol(lfsr.nobrain)){
  for(j in 1:ncol(lfsr.nobrain)){
    sig.row=which(a[,i]>0.5)#&lfsr.mash[,i]<thresh)##one of the tissues close to max effect and satisfies lfsr threshold
    sig.col=which(a[,j]>0.5)#&lfsr.mash[,j]<thresh)
    shared.het.nobrain[i,j]=length(intersect(sig.row,sig.col))/length(union(sig.row,sig.col))
 }

}

heatmap.2(shared.het.nobrain,density="none",trace="none",dendrogram = "none",col=redblue(256),main=paste0("Proportion Shared Homogeneity"),cexRow=0.5,cexCol=0.5,symm = T,key = FALSE)
mtext("Excluding Brain")

rm(a)
a=het.norm(effectsize = pm.mash.brain.only)##for each gene, normalize by max effect

shared.het.brainonly=matrix(NA,ncol=10,nrow=10)
colnames(shared.het.brainonly)=rownames(shared.het.brainonly)=tissue.names[c(7:16)]
for(i in 1:ncol(lfsr.brain.only)){
  for(j in 1:ncol(lfsr.brain.only)){
    sig.row=which(a[,i]>0.5)#&lfsr.mash[,i]<thresh)##one of the tissues close to max effect and satisfies lfsr threshold
    sig.col=which(a[,j]>0.5)#&lfsr.mash[,j]<thresh)
    shared.het.brainonly[i,j]=length(intersect(sig.row,sig.col))/length(union(sig.row,sig.col))
 }

}


heatmap.2(shared.het.brainonly,density="none",trace="none",dendrogram = "none",col=redblue(256),main="",cexRow=0.5,cexCol=0.5,symm = T,key=FALSE)
mtext("Brain Only")
```


