---
title: "sharedsigeffects"
output: html_document
---

Perform the analysis with separate analyses:
```{r setup, include=FALSE}
library('knitr')
knitr::opts_chunk$set(cache=TRUE)
opts_chunk$set(fig.path = "/Users/sarahurbut/Dropbox/PaperEdits/Paper/Figures/") 
```

```{r separate,echo=FALSE}
library(gplots)
library(ggplot2)

lfsr.all=read.table("~/Dropbox/Aug12/Aug13withEDlfsr.txt")[,-1]
lfsr.mash=lfsr.all
lfsr.nobrain=read.table("~/gtexresults_matrixash/withoutbrain//nobrainlfsr.txt")[,-1]

maxz=read.table("~/Dropbox/jul3/maxz.txt")

standard.error=read.table("~/gtexresults_matrixash/Data/standard.error.txt")

pm.mash=as.matrix(read.table("~/Dropbox/Aug12/Aug13withEDposterior.means.txt")[,-1])

pm.mash.beta=pm.mash*standard.error

pm.mash.nobrain=as.matrix(read.table("~/gtexresults_matrixash/withoutbrain/nobrainposterior.means.txt")[,-1])*standard.error[,-c(7:16)]

pm.mash.brain.only=as.matrix(read.table("~/Dropbox/BrainOnly//brainonlyposterior.means.txt")[,-1])*standard.error[,c(7:16)]
lfsr.brainonly=read.table("~/Dropbox/BrainOnly/brainonlylfsr.txt")[,-1]



pm.mash.nobrain=pm.mash.nobrain[rowSums(lfsr.nobrain<0.05)>0,]
lfsr.nobrain=lfsr.nobrain[rowSums(lfsr.nobrain<0.05)>0,]



pm.mash.brain.only=pm.mash.brain.only[rowSums(lfsr.brainonly<0.05)>0,]
lfsr.brainonly=lfsr.brainonly[rowSums(lfsr.brainonly<0.05)>0,]

pm.mash.beta=pm.mash.beta[rowSums(lfsr.mash<0.05)>0,]
lfsr.mash=lfsr.mash[rowSums(lfsr.mash<0.05)>0,]

brain.only.order=read.table("~/Dropbox/brain.only.order.txt")[,1]
exclude.brain.order=read.table("~/Dropbox/excludebrainorder.txt")[,1]
all.tissue.order=read.table("~/Dropbox/alltissueorder.txt")[,1]
```


```{r sep.foldchange.sig,echo=FALSE}
thresh=0.05

sign.mat=matrix(NA,nrow=44,ncol=44)
shared.fold.size=matrix(NA,nrow = ncol(lfsr.mash),ncol=ncol(lfsr.mash))
for(i in 1:ncol(lfsr.mash)){
  for(j in 1:ncol(lfsr.mash)){
    sig.row=which(lfsr.mash[,i]<thresh)
    sig.col=which(lfsr.mash[,j]<thresh)
    a=(union(sig.row,sig.col))
    #a=(intersect(sig.row,sig.col))
    #quotient=abs(pm.mash.beta[a,i]/pm.mash.beta[a,j])
    quotient=(pm.mash.beta[a,i]/pm.mash.beta[a,j])##divide effect sizes
    ##divide effect sizes
    #shared.fold.size[i,j]=mean(quotient>0.5&quotient<2)
    sign.mat[i,j]=(mean(quotient<0))
  }}


colnames(shared.fold.size)=colnames(maxz)
rownames(shared.fold.size)=colnames(maxz)

########

colnames(lfsr.nobrain)=colnames(maxz)[-c(7:16)]


shared.fold.size.nobrain=matrix(NA,nrow = ncol(lfsr.nobrain),ncol=ncol(lfsr.nobrain))
for(i in 1:ncol(lfsr.nobrain)){
  for(j in 1:ncol(lfsr.nobrain)){
    sig.row=which(lfsr.nobrain[,i]<thresh)
    sig.col=which(lfsr.nobrain[,j]<thresh)
    a=(union(sig.row,sig.col))
    #quotient=abs(pm.mash.nobrain[a,i]/pm.mash.nobrain[a,j])
    quotient=(pm.mash.nobrain[a,i]/pm.mash.nobrain[a,j])##divide effect sizes
    shared.fold.size.nobrain[i,j]=mean(quotient>0.5&quotient<2)
  }}


colnames(shared.fold.size.nobrain)=colnames(lfsr.nobrain)
rownames(shared.fold.size.nobrain)=colnames(lfsr.nobrain)
####



colnames(lfsr.brainonly)=colnames(maxz)[c(7:16)]

shared.fold.size.brainonly=matrix(NA,nrow = ncol(lfsr.brainonly),ncol=ncol(lfsr.brainonly))
for(i in 1:ncol(lfsr.brainonly)){
  for(j in 1:ncol(lfsr.brainonly)){
    sig.row=which(lfsr.brainonly[,i]<thresh)
    sig.col=which(lfsr.brainonly[,j]<thresh)
    a=(union(sig.row,sig.col))
    #quotient=abs(pm.mash.brain.only[a,i]/pm.mash.brain.only[a,j])
    quotient=(pm.mash.brain.only[a,i]/pm.mash.brain.only[a,j])##divide effect sizes
    shared.fold.size.brainonly[i,j]=mean(quotient>0.5&quotient<2)
  }

}


colnames(shared.fold.size.brainonly)=colnames(lfsr.brainonly)
rownames(shared.fold.size.brainonly)=colnames(lfsr.brainonly)
####

# heatmap.2(shared.fold.size,##Rowv=FALSE,Colv=FALSE,
#           symm=TRUE,dendrogram="none",density="none",trace="none",col=redblue,main=paste0("eQTL in either tissues and within 2-fold"),
#           cexRow=0.5,cexCol=0.5,cex.main=0.5,breaks=seq(0.35,1,0.01)
#           )
# mtext("Defined as QTL if LFSR<0.05")
# 
# excludebrainorder=heatmap.2(shared.fold.size.nobrain,##Rowv=FALSE,Colv=FALSE,
#           symm=TRUE,dendrogram="none",density="none",trace="none",col=redblue,main=paste0("eQTL in either tissues and within 2-fold"),cexRow=0.5,cexCol=0.5,cex.main=0.5,breaks=seq(0.35,1,0.01))$rowInd
# mtext("Defined as QTL if LFSR<0.05,SEP")
# 
# brainorder=heatmap.2(shared.fold.size.brainonly,##Rowv=FALSE,Colv=FALSE,
#         symm=TRUE,dendrogram="none",density="none",trace="none",col=redblue,main=paste0("eQTL in either tissues and within 2-fold"),cexRow=0.5,cexCol=0.5,cex.main=0.5,breaks=seq(0.35,1,0.01)
#         )$rowInd
# mtext("Defined as QTL if LFSR<0.05,SEP")

```

We could also try this with the orders induced from sharing by effect size:

```{r effectorderfoldsig,echo=F}
library('colorRamps')

brain.only.order=read.table("~/Dropbox/brain.only.order.txt")[,1]
exclude.brain.order=read.table("~/Dropbox/excludebrainorder.txt")[,1]
all.tissue.order=read.table("~/Dropbox/alltissueorder.txt")[,1]

heatmap.2(shared.fold.size[rev(all.tissue.order),all.tissue.order],Rowv=FALSE,Colv=FALSE,
          symm=TRUE,dendrogram="none",density="none",trace="none",#col=redblue,
          col=blue2green,main=paste0("eQTL in either tissues and within 2-fold,SUB"),
          cexRow=0.5,cexCol=0.5,cex.main=0.5,breaks=seq(0.35,1,0.01))
          
mtext("Defined as QTL if LFSR<0.05")
heatmap.2(shared.fold.size.nobrain[rev(exclude.brain.order),exclude.brain.order],Rowv=FALSE,Colv=FALSE,
          symm=TRUE,dendrogram="none",density="none",trace="none",col=blue2green,main=paste0("eQTL in either tissues and within 2-fold,SUB"),cexRow=0.5,cexCol=0.5,cex.main=0.5,breaks=seq(0.35,1,0.01))$rowInd
mtext("Defined as QTL if LFSR<0.05")

heatmap.2(shared.fold.size.brainonly[rev(brain.only.order),brain.only.order],Rowv=FALSE,Colv=FALSE,
        symm=TRUE,dendrogram="none",density="none",trace="none",col=blue2green,main=paste0("eQTL in either tissues and within 2-fold,SUB"),cexRow=0.5,cexCol=0.5,cex.main=0.5,breaks=seq(0.35,1,0.01))$rowInd
mtext("Defined as QTL if LFSR<0.05")
```



Repeat with all

```{r alltissuesignif, echo=FALSE}
lfsr.mash=read.table("~/Dropbox/Aug12/Aug13withEDlfsr.txt")[,-1]
pm.mash=as.matrix(read.table("~/Dropbox/Aug12/Aug13withEDposterior.means.txt")[,-1])
pm.mash.beta=pm.mash*standard.error
rm(lfsr.brainonly)
rm(lfsr.nobrain)
lfsr.brainonly=lfsr.all[,c(7:16)]
lfsr.nobrain=lfsr.brain.only=lfsr.all[,-c(7:16)]

rm(pm.mash.brain.only)
rm(pm.mash.nobrain)

pm.mash.brain.only=pm.mash.beta[,c(7:16)]
pm.mash.nobrain=pm.mash.beta[,-c(7:16)]



pm.mash.nobrain=pm.mash.nobrain[rowSums(lfsr.nobrain<0.05)>0,]
lfsr.nobrain=lfsr.nobrain[rowSums(lfsr.nobrain<0.05)>0,]



pm.mash.brain.only=pm.mash.brain.only[rowSums(lfsr.brainonly<0.05)>0,]
lfsr.brainonly=lfsr.brainonly[rowSums(lfsr.brainonly<0.05)>0,]

pm.mash.beta=pm.mash.beta[rowSums(lfsr.mash<0.05)>0,]
lfsr.mash=lfsr.mash[rowSums(lfsr.mash<0.05)>0,]


thresh=0.05

shared.fold.size=matrix(NA,nrow = ncol(lfsr.mash),ncol=ncol(lfsr.mash))
for(i in 1:ncol(lfsr.mash)){
  for(j in 1:ncol(lfsr.mash)){
    sig.row=which(lfsr.mash[,i]<thresh)
    sig.col=which(lfsr.mash[,j]<thresh)
    a=(union(sig.row,sig.col))
    #quotient=abs(pm.mash.beta[a,i]/pm.mash.beta[a,j])
    quotient=(pm.mash.beta[a,i]/pm.mash.beta[a,j])##divide effect sizes
    shared.fold.size[i,j]=mean(quotient>0.5&quotient<2)
  }}


colnames(shared.fold.size)=colnames(maxz)
rownames(shared.fold.size)=colnames(maxz)

########

colnames(lfsr.nobrain)=colnames(maxz)[-c(7:16)]


shared.fold.size.nobrain=matrix(NA,nrow = ncol(lfsr.nobrain),ncol=ncol(lfsr.nobrain))
for(i in 1:ncol(lfsr.nobrain)){
  for(j in 1:ncol(lfsr.nobrain)){
    sig.row=which(lfsr.nobrain[,i]<thresh)
    sig.col=which(lfsr.nobrain[,j]<thresh)
    a=(union(sig.row,sig.col))
    #quotient=abs(pm.mash.nobrain[a,i]/pm.mash.nobrain[a,j])##divide effect sizes
    quotient=(pm.mash.nobrain[a,i]/pm.mash.nobrain[a,j])
    shared.fold.size.nobrain[i,j]=mean(quotient>0.5&quotient<2)
  }}


colnames(shared.fold.size.nobrain)=colnames(lfsr.nobrain)
rownames(shared.fold.size.nobrain)=colnames(lfsr.nobrain)
####



colnames(lfsr.brainonly)=colnames(maxz)[c(7:16)]

shared.fold.size.brainonly=matrix(NA,nrow = ncol(lfsr.brainonly),ncol=ncol(lfsr.brainonly))
for(i in 1:ncol(lfsr.brainonly)){
  for(j in 1:ncol(lfsr.brainonly)){
    sig.row=which(lfsr.brainonly[,i]<thresh)
    sig.col=which(lfsr.brainonly[,j]<thresh)
    a=(union(sig.row,sig.col))
    #quotient=abs(pm.mash.brain.only[a,i]/pm.mash.brain.only[a,j])
    quotient=(pm.mash.brain.only[a,i]/pm.mash.brain.only[a,j])##divide effect sizes
    shared.fold.size.brainonly[i,j]=mean(quotient>0.5&quotient<2)
  }

}


colnames(shared.fold.size.brainonly)=colnames(lfsr.brainonly)
rownames(shared.fold.size.brainonly)=colnames(lfsr.brainonly)
####

# heatmap.2(shared.fold.size,##Rowv=FALSE,Colv=FALSE,
#           symm=TRUE,dendrogram="none",density="none",trace="none",col=redblue,main=paste0("eQTL in either tissues and within 2-fold"),
#           cexRow=0.5,cexCol=0.5,cex.main=0.5,breaks=seq(0.35,1,0.01)
#           )
# mtext("Defined as QTL if LFSR<0.05")
# 
# excludebrainorder=heatmap.2(shared.fold.size.nobrain,##Rowv=FALSE,Colv=FALSE,
#           symm=TRUE,dendrogram="none",density="none",trace="none",col=redblue,main=paste0("eQTL in either tissues and within 2-fold"),cexRow=0.5,cexCol=0.5,cex.main=0.5,breaks=seq(0.35,1,0.01))$rowInd
# mtext("Defined as QTL if LFSR<0.05,SEP")
# 
# brainorder=heatmap.2(shared.fold.size.brainonly,##Rowv=FALSE,Colv=FALSE,
#         symm=TRUE,dendrogram="none",density="none",trace="none",col=redblue,main=paste0("eQTL in either tissues and within 2-fold"),cexRow=0.5,cexCol=0.5,cex.main=0.5,breaks=seq(0.35,1,0.01)
#         )$rowInd
# mtext("Defined as QTL if LFSR<0.05,SEP")

```

We could also try this with the orders induced from sharing by effect size:

```{r effectorderfoldsigalltissue,echo=F}
library('colorRamps')
brain.only.order=read.table("~/Dropbox/brain.only.order.txt")[,1]
exclude.brain.order=read.table("~/Dropbox/excludebrainorder.txt")[,1]
all.tissue.order=read.table("~/Dropbox/alltissueorder.txt")[,1]

heatmap.2(shared.fold.size[rev(all.tissue.order),all.tissue.order],Rowv=FALSE,Colv=FALSE,
          symm=TRUE,dendrogram="none",density="none",trace="none",col=blue2green,main=paste0("eQTL in either tissues and within 2-fold,GLOBAL"),
          cexRow=0.5,cexCol=0.5,cex.main=0.5,breaks=seq(0.35,1,0.01))

mtext("Defined as QTL if LFSR<0.05")

heatmap.2(shared.fold.size.nobrain[rev(exclude.brain.order),exclude.brain.order],Rowv=FALSE,Colv=FALSE,
          symm=TRUE,dendrogram="none",density="none",trace="none",col=blue2green,main=paste0("eQTL in either tissues and within 2-fold,GLOBAL"),cexRow=0.5,cexCol=0.5,cex.main=0.5,breaks=seq(0.35,1,0.01))$rowInd
mtext("Defined as QTL if LFSR<0.05")

heatmap.2(shared.fold.size.brainonly[rev(brain.only.order),brain.only.order],Rowv=FALSE,Colv=FALSE,
        symm=TRUE,dendrogram="none",density="none",trace="none",col=blue2green,main=paste0("eQTL in either tissues and within 2-fold,GLOBAL"),cexRow=0.5,cexCol=0.5,cex.main=0.5,breaks=seq(0.35,1,0.01))$rowInd
mtext("Defined as QTL if LFSR<0.05")
```


Tissuespecific by effect:

```{r barplotspec,echo=FALSE}
rm(pm.mash.beta)
rm(lfsr.mash)
source("~/gtexresults_matrixash/Analysis/normfuncs.R")

lfsr.mash=read.table("~/Dropbox/Aug12/Aug13withEDlfsr.txt")[,-1]
pm.mash=as.matrix(read.table("~/Dropbox/Aug12/Aug13withEDposterior.means.txt")[,-1])
pm.mash.beta=pm.mash*standard.error

nsig=rowSums(lfsr.mash<thresh)
pm.mash.beta.norm=het.norm(effectsize = pm.mash.beta)
pm.mash.beta.norm=pm.mash.beta.norm[(nsig>0),]
lfsr.mash=as.matrix(lfsr.mash[nsig>0,])
colnames(lfsr.mash)=colnames(maxz)


thresh=0.05
barplot(apply(lfsr.mash[which(rowSums(lfsr.mash<=thresh)==1),],2,function(x){sum(x<=thresh)}),las=2,cex.names=0.5,main=paste0("Number of eQTL with LFSR<",0.05," in Single Tissue"),ylim=c(0,500))


###Now plot the number of normalized effects greater than 0.5 for each tissue, given that those effects were significant in at least one tissue
#barplot(apply(pm.mash.beta.norm[which(rowSums(pm.mash.beta.norm>0.5)==1),],2,function(x){sum(x>0.5)}),las=2,cex.names=0.5,main=paste0("Number of eQTL with Bjnorm>0.5 in Single Tissue"),ylim=c(0,500))



###Now plot the number of normalized effects greater than 0.5 for each tissue, given that those effects were significant in that tissue

a=which(rowSums(pm.mash.beta.norm>0.5)==1)
lfsr.fold=as.matrix(lfsr.mash[a,])
pm=as.matrix(pm.mash.beta.norm[a,])
tspec=NULL
for(i in 1:ncol(pm)){
  #tspec[i]=sum(lfsr.fold[,i]<0.05&pm[,i]>0.5)
  tspec[i]=sum(pm[,i]>0.5)
  }##check to see that the effect is significant and greater than 0.5 max effect in only that tissue

tspec=as.matrix(tspec);rownames(tspec)=colnames(maxz)

barplot(t(tspec),main=paste0("Number of eQTL with Bjnorm>0.5 in one Tissue"),las=2,ylim=c(0,500),cex.names=0.5)



###Now plot the number of normalized effects greater than 0.5 for each tissue, given that those effects were significant in only one tissue

b=which(rowSums(lfsr.mash<0.05)==1&rowSums(pm.mash.beta.norm>0.5)==1)
#lfsr.fold=as.matrix(lfsr.mash[b,])
#pm=as.matrix(pm.mash.beta.norm[b,])
tspec=NULL
for(i in 1:ncol(pm)){
  tspec[i]=sum(pm.mash.beta.norm[b,i]>0.5&lfsr.mash[b,]<0.05)}##check to see that the effect is significant and greater than 0.5 max effect in only that tissue

tspec=as.matrix(tspec);rownames(tspec)=colnames(maxz)

barplot(t(tspec),main=paste0("Number of eQTL with LFSR<0.05 in only one tissue and Bjnorm>0.5 in one Tissue"),las=2,ylim=c(0,500))
```


