---
title: "uk3"
output: pdf_document
---
Here we plot the correlation matrix and the first 3 eigenvectors of Uk3.

```{r}
library('knitr')

knitr::opts_chunk$set(cache=TRUE)
opts_chunk$set(fig.path = "/Users/sarahurbut/Dropbox/PaperEdits/Paper/Figures/") 
covmat=readRDS("../Data/covmatAug13withED.rds")

z.stat=read.table("../Data/maxz.txt")
names=colnames(z.stat)
pis=readRDS("../Data/pisAug13withED.rds")$pihat
pi.mat=matrix(pis,ncol=54,nrow=22,byrow = T)
```

```{r corplotuk3,fig.height=8,fig.width=8}
library(gplots)
library(ggplot2)
library('colorRamps')
#install.packages("fields")
library(fields)
k=3
hclust.2=function (d, method = "average", members = NULL) {hclust(d, method, members)}
  x=cov2cor(covmat[[k]])
x[x<0]=0
  colnames(x)=names
  rownames(x)=names
# h=heatmap.2((x),symm=TRUE,dendrogram="none",density="none",trace="none",col=blue2green(256),main=paste0("Cov2CorU",k,"pihat=",round(colSums(pi.mat)[k],2)),cexRow=0.5,cexCol=0.5,hclustfun = hclust.2)
# 
# heatmap.2((x[h$rowInd,h$rowInd]),Colv=FALSE,Rowv=FALSE,symm=TRUE,dendrogram="none",density="none",trace="none",col=blue2green(256),main=paste0("Cov2CorU",k,"pihat=",round(colSums(pi.mat)[k],2)),cexRow=0.5,cexCol=0.5,hclustfun = hclust.2)



h=heatmap.2((x),#symm=TRUE,
            dendrogram="none",density="none",trace="none",col=blue2green(256),main=paste0("Cov2CorU",k,"pihat=",round(colSums(pi.mat)[k],2)),cexRow=0.5,cexCol=0.5)

heatmap.2((x[h$rowInd,h$rowInd]),Colv=FALSE,Rowv=FALSE,symm=TRUE,dendrogram="none",density="none",trace="none",col=blue2green(256),main=paste0("Cov2CorU",k,"pihat=",round(colSums(pi.mat)[k],2)),cexRow=0.5,cexCol=0.5,hclustfun = hclust.2)

#write.table(h$rowInd,"uk3rowindices.txt")


smat=(x[h$rowInd,h$rowInd])
smat[lower.tri(smat)] <- NA


heatmap.2(smat,#symm=TRUE,
          Rowv=FALSE,Colv=FALSE,
          dendrogram="none",density="none",trace="none",#col=redblue,
          col=blue2green(256),
          main=paste0("Cov2CortUk3"),
          cexRow=0.5,cexCol=0.5,cex.main=0.5)


missing.tissues=c(7,8,19,20,24,25,31,34,37)
color.gtex=read.table("../Data/GTExColors.txt",sep = '\t', comment.char = '')[-missing.tissues,]
col = as.character(color.gtex[,2])

library('corrplot')


colnames(x)=NULL
corrplot((x[h$rowInd,h$rowInd]),type="upper",cl.lim=c(0,1),tl.col=col[h$rowInd],tl.cex=0.8,method="color",col=rep(blue2green(256),2))


```


Let's try with different ordering:

```{r difforder, eval=FALSE}

all.tissue.order=read.table("../../Dropbox/alltissueorder.txt")[,1]

  x=cov2cor(covmat[[k]])
x[x<0]=0

  colnames(x)=names
  rownames(x)=names


smat=x[(all.tissue.order),(all.tissue.order)]
smat[lower.tri(smat)] <- NA

heatmap.2(smat,#symm=TRUE,
          Rowv=FALSE,Colv=FALSE,
          dendrogram="none",density="none",trace="none",#col=redblue,
          col=blue2green(256),
          main=paste0("Cov2CortUk3"),
          cexRow=0.5,cexCol=0.5,cex.main=0.5)






```




Eigenplots:

```{r eigenplots}
missing.tissues=c(7,8,19,20,24,25,31,34,37)
color.gtex=read.table("../Data/GTExColors.txt",sep = '\t', comment.char = '')[-missing.tissues,]

names=colnames(z.stat)
vold=svd(covmat[[k]])$v;u=svd(covmat[[k]])$u

v=vold[h$rowInd,]##shuffle so correct order
names=names[h$rowInd]
color.gtex=color.gtex[h$rowInd,]
for(j in 1:3){
barplot(v[,j]/v[,j][which.max(abs(v[,j]))],names="",cex.names=0.5,las=2,main=paste0("EigenVector",j,"Uk",k),col = as.character(color.gtex[,2]))}

```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
