---
title: "Tspec"
author: "Sarah Urbut, Gao Wang, Peter Carbonetto and Matthew Stephens"
output: workflowr::wflow_html
---

*Add text here.*

```{r knitr, message = FALSE, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, fig.width = 8,
                      fig.height = 4,fig.align = "center",
                      comment = "#")
```

## Set up environment

First, we load some functions defined for mash analyses.

```{r load-functions}
source("../code/normfuncs.R")
```

*Add text here.*

```{r}
thresh <- 0.05
```

## Load data and mash results

Load some GTEx summary statistics, as well as some of the results
generated from the mash analysis of the GTEx data.

```{r load-results}
out <- readRDS("../data/MatrixEQTLSumStats.Portable.Z.rds")
maxb           <- out$test.b
maxz           <- out$test.z
standard.error <- out$test.s
out <- readRDS(paste("../output/MatrixEQTLSumStats.Portable.Z.coved.K3.P3",
                     "lite.single.expanded.V1.posterior.rds",sep = "."))
pm.mash      <- out$posterior.means
lfsr.mash    <- out$lfsr
pm.mash.beta <- pm.mash * standard.error
```

```{r}
nsig                <- rowSums(lfsr.mash<thresh)
pm.mash.beta.norm   <- het.norm(effectsize = pm.mash.beta)
pm.mash.beta.norm   <- pm.mash.beta.norm[(nsig>0),]
lfsr.mash           <- as.matrix(lfsr.mash[nsig>0,])
colnames(lfsr.mash) <- colnames(maxz)
```

```{r}
missing.tissues <- c(7,8,19,20,24,25,31,34,37)
color.gtex      <- read.table("../data/GTExColors.txt",sep = '\t',
                              comment.char = '')[-missing.tissues,]
col = as.character(color.gtex[,2])
```

```{r}
a=which(rowSums(pm.mash.beta.norm>0.5)==1)
lfsr.fold=as.matrix(lfsr.mash[a,])
pm <- as.matrix(pm.mash.beta.norm[a,])
tspec=NULL
for(i in 1:ncol(pm)){
  tspec[i]=sum(pm[,i]>0.5)
}
tspec           <- as.matrix(tspec)
rownames(tspec) <- colnames(maxz)
```

```{r}
barplot(as.numeric(t(tspec)),las = 2,cex.names = 0.3,col = col,
        names = colnames(lfsr.fold))
```
